"""Add personality memory fields

Revision ID: 9e8af5c916ea
Revises: 
Create Date: 2025-07-11 01:44:14.575256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8af5c916ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('slang', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('style', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('beliefs', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prefers_savage_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('favorite_scholars', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_scholars')
        batch_op.drop_column('prefers_savage_mode')
        batch_op.drop_column('interests')
        batch_op.drop_column('beliefs')
        batch_op.drop_column('style')
        batch_op.drop_column('slang')
        batch_op.drop_column('tone')

    # ### end Alembic commands ###
